### ISSUE TITLE
Sort by options have no effect on post feed

### ISSUE THREAD

**Issue by tobias-g1** [steemgigs/steemgigs#9]
#### Expected behavior
When I use any of the sort options to sort the posts shown within the feed, the feed should be sorted based on my selection. For example, If I select new as my sort-by option, the feed should show newest posts first ordered from newest to oldest. 

#### Actual behavior
Using any of the sort-by options shown to the top right of the feed have no effect on the way the feed is sorted. 

#### How to reproduce

1. Visit [SteemGigs.org](https://steemgigs.org)
2. When on the home page you will see a hero banner directly underneath the top navigation, underneath this you will see a post feed. To the right of this, you will see a sort-by drop down which has the following options: Trending, New, Active, Hot, Promoted
3. Take note of the current order of the feed and using the drop-down select New
4. There will be no change of how the feed is displayed. 
5. Repeat step 3 for the selection of Active, Hot, Trending & Promoted.

* Browser: Google Chrome Version 64.0.3282.186 (Official Build) (64-bit)
* Operating system: MacOS HighSierra Version 10.13 (17A365)

#### Recording Of The Bug
Please use the image below to view the issue which I discuss:

![Mar-14-2018 19-08-06.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1521055925/nulpmwlimbymae2ut7hc.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@tobias-g/sort-by-options-have-no-effect-on-post-feed">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by jalasem** [comment]
We need community contribution to make our work faster, most of these are on our task board, just fixing critical issues are what is on our top priority list for now. Both frontend and backend are now open source.

**Comment by steemgigs** [comment]
Very special tobias. Thank you for being very supportive since day one. Your contributions have been bookmarked since day one and we will work on them gradually. Yes, that portion (sorting options) had mostly placeholders and was a feature in the making. 

>The code, both back and front end is now open-source, so we can move faster.

## A little addition for the developer who gets to take this issue up.
1. On the list of **sorting options** (the drop-down), kindly remove **"promoted"** as it is not needed. To replace that, use **"Reputation"**. 
As we don't have escrow yet and rely mostly on transparency of steem and general reputation, we will like to have the option **to sort by "reputation".** 
>Perhaps, we can also have a system in the future where gigs from accounts with reputation of **0 or negative**  are graded out but that can come in the future. (optional for now)

2. You can also add **"free"** i.e **sort by free** as i feel people may want to personalize their feed, to see steemgigs that are free. 
>On [steemgigs](https://steemgigs.org), there are bound to be free services, so you can have the option feature only gigs with a price of zero (0) or free.

3. **"Trending"** : Ofcourse "sort by trending" will be implemented!

4. **"Active"**: may involve displaying posts that haven't pay out yet and are still voteable on. 
> Consider getting some ideas from how steemit or busy measure "active" or "hot".
(Notice that it is already possible to vote (with slider) directly on our UI.)

**"Hot"**: will involve sorting according to **level of interaction**. So, perhaps, "posts with more comment interaction etc will be displayed ahead of those gigs with less (in that order)
> Consider getting some ideas from how steemit or busy measure "active" or "hot".

Please note that the home page has various segments.
The top part is the main part, displaying #steemgigs (offered services). The sorting options for this part will be:
Trending
Reputation
New
Active
Hot
Free

The next part called **"featured #steemgigs"**:
Trending
Reputation
New
Active
Hot
Free

Then scrolling down, you will find **#gigrequests**:
Trending
Reputation
New
Active
Hot
**(This doesn't need to have the "free" option)**

And scrolling down further, you will see **"testimonials"**:
Trending
Reputation
New
Active
Hot
**(This also doesn't need to have the "free" option)**

Join **[steemgigs on slack](https://join.slack.com/t/steemgigs/shared_invite/enQtMzMxNDIzMzM5MTkxLWRhNDgyMjc5YjNmZjJmMWYzNGU3ZTcxMjFjMTU5YWI5ZGNhMjA5ZDdlNWIwNjcwNjRiMzc3NDRiMzk2MDU4MzI)** for more development discussion

**Comment by tobias-g1** [comment]
Issue #68 now represents the current vision for sorting.
